#define OR                              1
#define AND                             2
#define NOT                             3
#define LT                              4
#define LE                              5
#define GT                              6
#define GE                              7
#define NE                              8
#define EQ                              9
#define PLUS                           10
#define MINUS                          11
#define TIMES                          12
#define DIVDE                          13
#define DOT                            14
#define PROGRAM                        15
#define IDENTIFIER                     16
#define SEMICOLON                      17
#define VAR                            18
#define FUNCTION                       19
#define COLON                          20
#define COMMA                          21
#define INTEGER                        22
#define FLOAT                          23
#define ARRAY                          24
#define LBRACKET                       25
#define RBRACKET                       26
#define OF                             27
#define INTNUM                         28
#define DOTDOT                         29
#define ASSIGN                         30
#define IF                             31
#define ELSE                           32
#define THEN                           33
#define DO                             34
#define WHILE                          35
#define READ                           36
#define LPAREN                         37
#define RPAREN                         38
#define WRITE                          39
#define RETURN                         40
#define T_BEGIN                        41
#define END                            42
#define DIVIDE                         43
#define STRING                         44
#define FLOATCON                       45
